GET http://bcn-fem-tech-http-store-anag.herokuapp.com/products
Accept: application/json

###
POST http://bcn-fem-tech-http-store-anag.herokuapp.com/products
Content-Type: application/x-www-form-urlencoded

name=alpargataas&price=13

###


